In [1]:
import pandas as pd
import sys, os
project_root = os.path.abspath(os.path.join(os.getcwd(), "../"))
sys.path.append(project_root)
from src.data_profiling import DiabetesProfiling;

In [2]:
df =pd.read_csv("../data/diabetes.csv")

In [3]:

profiler = DiabetesProfiling(df)
profiler.run_all()

====== DIABETES DATA OVERVIEW ======
Total Observations: 403
Total Features: 19

Data Types Summary:

float64    13
int64       3
object      3
Name: count, dtype: int64

First 3 Rows:

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
0,1000,203.0,82,56.0,3.6,4.31,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,NaN,NaN,29.0,38.0,720.0
1,1001,165.0,97,24.0,6.9,4.44,Buckingham,29,female,64.0,218.0,large,112.0,68.0,NaN,NaN,46.0,48.0,360.0
2,1002,228.0,92,37.0,6.2,4.64,Buckingham,58,female,61.0,256.0,large,190.0,92.0,185.0,92.0,49.0,57.0,180.0

====== SUMMARY STATISTICS ======

--- Clinical / Lab Results ---

,count,mean,std,min,25%,50%,75%,max
chol,402.0,207.845771,44.445557,78.00,179.00,204.00,230.0,443.000000
stab.glu,403.0,106.672457,53.076655,48.00,81.00,89.00,106.0,385.000000
hdl,402.0,50.445274,17.262626,12.00,38.00,46.00,59.0,120.000000
ratio,402.0,4.521642,1.727886,1.50,3.20,4.20,5.4,19.299999
glyhb,390.0,5.589769,2.242595,2.68,4.38,4.84,5.6,16.110001

--- Physical / Body Measurements ---

        count        mean        std   min    25%    50%    75%    max
age     403.0   46.851117  16.312333  19.0   34.0   45.0   60.0   92.0
height  398.0   66.020101   3.918515  52.0   63.0   66.0   69.0   76.0
weight  402.0  177.592040  40.340666  99.0  151.0  172.5  200.0  325.0
waist   401.0   37.900249   5.729313  26.0   33.0   37.0   41.0   56.0
hip     401.0   43.039900   5.656713  30.0   39.0   42.0   46.0   64.0

--- Categorical Variable Distribution ---

Value Counts for location:

location
Louisa        203
Buckingham    200
Name: count, dtype: int64

Value Counts for gender:

gender
female    234
male      169
Name: count, dtype: int64

Value Counts for frame:

frame
medium    184
small     104
large     103
Name: count, dtype: int64

====== MISSING DATA SUMMARY ======

          Missing Values  Percentage (%)
bp.2s                262       65.012407
bp.2d                262       65.012407
glyhb                 13        3.225806
frame                 12        2.977667
height                 5        1.240695
bp.1s                  5        1.240695
bp.1d                  5        1.240695
time.ppn               3        0.744417
waist                  2        0.496278
hip                    2        0.496278
chol                   1        0.248139
hdl                    1        0.248139
ratio                  1        0.248139
weight                 1        0.248139

====== DUPLICATE ROW CHECK ======
Duplicate Rows Found: 0

====== OUTLIER DETECTION (IQR METHOD) ======

     Feature  Outlier Count  Percentage (%)  Lower Bound  Upper Bound
4      glyhb             57       14.143921         2.55         7.43
1   stab.glu             51       12.655087        43.50       143.50
2        hdl             13        3.225806         6.50        90.50
8      bp.1s             13        3.225806        83.00       185.00
9      bp.1d             13        3.225806        52.50       112.50
13       hip             13        3.225806        28.50        56.50
7     weight             11        2.729529        77.50       273.50
0       chol              9        2.233251       102.50       306.50
14  time.ppn              8        1.985112      -551.25      1158.75
3      ratio              6        1.488834        -0.10         8.70
10     bp.2s              6        1.488834       103.50       195.50
12     waist              2        0.496278        21.00        53.00
6     height              1        0.248139        54.00        78.00

> Note: High outliers in 'stab.glu' or 'glyhb' are common in diabetic datasets.

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
0,1000,203.0,82,56.0,3.6,4.310000,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,NaN,NaN,29.0,38.0,720.0
1,1001,165.0,97,24.0,6.9,4.440000,Buckingham,29,female,64.0,218.0,large,112.0,68.0,NaN,NaN,46.0,48.0,360.0
2,1002,228.0,92,37.0,6.2,4.640000,Buckingham,58,female,61.0,256.0,large,190.0,92.0,185.0,92.0,49.0,57.0,180.0
3,1003,78.0,93,12.0,6.5,4.630000,Buckingham,67,male,67.0,119.0,large,110.0,50.0,NaN,NaN,33.0,38.0,480.0
4,1005,249.0,90,28.0,8.9,7.720000,Buckingham,64,male,68.0,183.0,medium,138.0,80.0,NaN,NaN,44.0,41.0,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,41506,296.0,369,46.0,6.4,16.110001,Louisa,53,male,69.0,173.0,medium,138.0,94.0,130.0,94.0,35.0,39.0,210.0
399,41507,284.0,89,54.0,5.3,4.390000,Louisa,51,female,63.0,154.0,medium,140.0,100.0,146.0,102.0,32.0,43.0,180.0
400,41510,194.0,269,38.0,5.1,13.630000,Louisa,29,female,69.0,167.0,small,120.0,70.0,NaN,NaN,33.0,40.0,20.0
401,41752,199.0,76,52.0,3.8,4.490000,Louisa,41,female,63.0,197.0,medium,120.0,78.0,NaN,NaN,41.0,48.0,255.0
402,41756,159.0,88,79.0,2.0,NaN,Louisa,68,female,64.0,220.0,medium,100.0,72.0,NaN,NaN,49.0,58.0,900.0